import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { workspaceAgents } from '@agenthub/db'
import {
  ensureWorkerAgentContract,
  listWorkerRuntimeSpecificConfigFiles,
  type WorkerAgentContractWorkspace,
} from '../agent-contract'

type WorkspaceAgentRow = typeof workspaceAgents.$inferSelect

const BRIDGE_CONTEXT_START = '<!-- AGENTHUB:BRIDGE-RUNTIME-CONTEXT:START -->'
const BRIDGE_CONTEXT_END = '<!-- AGENTHUB:BRIDGE-RUNTIME-CONTEXT:END -->'

export interface WorkerBridgeContractProjection {
  contract: WorkerAgentContractWorkspace
  executionCwd: string
  bridgeRoot: string
  agentsPath: string
  soulPath: string
  skillsPath: string
}

export async function projectWorkerContractIntoBridgeCwd(input: {
  workerInstanceId?: string | null
  agent: WorkspaceAgentRow
  executionCwd?: string | null
  runtimeBase?: string | null
  room?: {
    roomId: string
    roomKind?: string | null
    providerRoomId?: string | null
    participantId?: string | null
    title?: string | null
  } | null
  task?: {
    taskId: string
    taskThreadId?: string | null
    runId?: string | null
    roomId?: string | null
    status?: string | null
    title?: string | null
    sharedTaskRelativeRoot?: string | null
    sharedTaskSpecPath?: string | null
    runtimeLeaseId?: string | null
  } | null
  controllerUrl?: string | null
  sharedStorageRoot?: string | null
}): Promise<WorkerBridgeContractProjection | null> {
  const executionCwd = input.executionCwd?.trim()
  const workerInstanceId = input.workerInstanceId?.trim()
  if (!executionCwd || !workerInstanceId) return null

  const contract = await ensureWorkerAgentContract({
    workerInstanceId,
    agent: input.agent,
    runtimeBase: input.runtimeBase,
    controllerUrl: input.controllerUrl,
    sharedStorageRoot: input.sharedStorageRoot,
    currentRooms: input.room ? [input.room] : undefined,
    currentTasks: input.task ? [input.task] : undefined,
  })
  const bridgeRoot = join(executionCwd, '.agenthub', 'worker-contract')
  const skillsPath = join(bridgeRoot, 'skills')
  mkdirSync(bridgeRoot, { recursive: true })

  copyIfExists(contract.soulPath, join(bridgeRoot, 'SOUL.md'))
  copyIfExists(contract.profilePath, join(bridgeRoot, 'profile.json'))
  copyIfExists(contract.runtimePath, join(bridgeRoot, 'runtime.json'))
  copyIfExists(contract.runtimeManifestPath, join(bridgeRoot, 'runtime-manifest.json'))
  copyIfExists(contract.statePath, join(bridgeRoot, 'state.json'))
  copyIfExists(contract.roomsPath, join(bridgeRoot, 'rooms.json'))
  copyIfExists(contract.tasksPath, join(bridgeRoot, 'tasks.json'))
  for (const fileName of listWorkerRuntimeSpecificConfigFiles()) {
    copyIfExists(join(contract.root, fileName), join(bridgeRoot, fileName))
  }
  if (existsSync(contract.skillsPath)) {
    cpSync(contract.skillsPath, skillsPath, { recursive: true, force: true })
  }

  const contractAgents = existsSync(contract.agentsPath)
    ? readFileSync(contract.agentsPath, 'utf8').trim()
    : ''
  upsertBridgeContext(join(executionCwd, 'AGENTS.md'), buildBridgeContext({
    contract,
    bridgeRoot,
    contractAgents,
  }))

  return {
    contract,
    executionCwd,
    bridgeRoot,
    agentsPath: join(executionCwd, 'AGENTS.md'),
    soulPath: join(bridgeRoot, 'SOUL.md'),
    skillsPath,
  }
}

function buildBridgeContext(input: {
  contract: WorkerAgentContractWorkspace
  bridgeRoot: string
  contractAgents: string
}) {
  return [
    BRIDGE_CONTEXT_START,
    '# AgentHub Worker Bridge Runtime Context',
    '',
    'This execution directory is used by an AgentHub-managed bridge Worker runtime.',
    'The canonical Worker contract is generated by AgentHub Controller and projected here before each run.',
    '',
    `- Contract root: ${input.contract.root}`,
    `- Projected contract root: ${input.bridgeRoot}`,
    `- Projected SOUL: ${join(input.bridgeRoot, 'SOUL.md')}`,
    `- Projected runtime manifest: ${join(input.bridgeRoot, 'runtime-manifest.json')}`,
    `- Projected skills: ${join(input.bridgeRoot, 'skills')}`,
    '',
    '## Runtime Rules',
    '- Treat this AGENTS.md as the local operating contract for the current CLI run.',
    '- Read .agenthub/worker-contract/SOUL.md for identity and long-lived behavior.',
    '- Read .agenthub/worker-contract/runtime-manifest.json for the runtime adapter contract.',
    '- Use .agenthub/worker-contract/skills/ for assigned AgentHub skills when present.',
    '- Continue to use Matrix Room timeline for communication, progress, clarification, and completion.',
    '',
    input.contractAgents ? '## Canonical Worker AGENTS.md' : '',
    input.contractAgents,
    BRIDGE_CONTEXT_END,
  ]
    .filter(Boolean)
    .join('\n')
}

function upsertBridgeContext(path: string, context: string) {
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : '# AgentHub Bridge Worker AGENTS\n'
  const start = existing.indexOf(BRIDGE_CONTEXT_START)
  const end = existing.indexOf(BRIDGE_CONTEXT_END)
  if (start >= 0 && end > start) {
    const before = existing.slice(0, start).trimEnd()
    const after = existing.slice(end + BRIDGE_CONTEXT_END.length).trimStart()
    writeFileSync(path, `${before}\n\n${context}${after ? `\n\n${after}` : ''}\n`, 'utf8')
    return
  }
  writeFileSync(path, `${existing.trimEnd()}\n\n${context}\n`, 'utf8')
}

function copyIfExists(from: string, to: string) {
  if (!existsSync(from)) return
  mkdirSync(dirname(to), { recursive: true })
  cpSync(from, to, { force: true })
}
