export const AppErrorCodes = {
  // 通用
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  TIMEOUT: 'TIMEOUT',

  // 校验 / 参数
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_JSON: 'INVALID_JSON',
  MISSING_FIELD: 'MISSING_FIELD',
  INVALID_UUID: 'INVALID_UUID',

  // 认证（当前单用户模式，预留）
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // 会话
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_CREATE_FAILED: 'SESSION_CREATE_FAILED',
  SESSION_DELETE_FAILED: 'SESSION_DELETE_FAILED',

  // 消息
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_UPDATE_FAILED: 'MESSAGE_UPDATE_FAILED',
  MESSAGE_PIN_FAILED: 'MESSAGE_PIN_FAILED',
  ORCHESTRATOR_PLAN_FAILED: 'ORCHESTRATOR_PLAN_FAILED',
  ORCHESTRATOR_DISPATCH_FAILED: 'ORCHESTRATOR_DISPATCH_FAILED',

  // Workspace
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_CREATE_FAILED: 'WORKSPACE_CREATE_FAILED',
  WORKSPACE_UPDATE_FAILED: 'WORKSPACE_UPDATE_FAILED',
  PROJECT_PATH_INVALID: 'PROJECT_PATH_INVALID',
  PROJECT_PATH_NOT_FOUND: 'PROJECT_PATH_NOT_FOUND',

  // 任务
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_EXECUTION_FAILED: 'TASK_EXECUTION_FAILED',
  TASK_MAX_RETRIES_EXCEEDED: 'TASK_MAX_RETRIES_EXCEEDED',
  TASK_CANCEL_FAILED: 'TASK_CANCEL_FAILED',

  // Agent / Code Agent
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_REPLY_FAILED: 'AGENT_REPLY_FAILED',
  CODE_AGENT_NOT_INSTALLED: 'CODE_AGENT_NOT_INSTALLED',
  CODE_AGENT_CONFIG_INVALID: 'CODE_AGENT_CONFIG_INVALID',
  CODE_AGENT_EXECUTION_FAILED: 'CODE_AGENT_EXECUTION_FAILED',

  // LLM
  LLM_REQUEST_FAILED: 'LLM_REQUEST_FAILED',
  LLM_RATE_LIMITED: 'LLM_RATE_LIMITED',
  LLM_INVALID_RESPONSE: 'LLM_INVALID_RESPONSE',
  MODEL_NOT_CONFIGURED: 'MODEL_NOT_CONFIGURED',

  // 编排器
  ORCHESTRATOR_RUN_NOT_FOUND: 'ORCHESTRATOR_RUN_NOT_FOUND',
  ORCHESTRATOR_RUN_FAILED: 'ORCHESTRATOR_RUN_FAILED',
  ORCHESTRATOR_PLAN_INVALID: 'ORCHESTRATOR_PLAN_INVALID',
  ORCHESTRATOR_SYNTHESIZE_FAILED: 'ORCHESTRATOR_SYNTHESIZE_FAILED',

  // 文件 / Artifact
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',
  DIFF_APPLY_FAILED: 'DIFF_APPLY_FAILED',
  DIFF_VALIDATION_FAILED: 'DIFF_VALIDATION_FAILED',

  // 设置 / 工具
  SETTINGS_SAVE_FAILED: 'SETTINGS_SAVE_FAILED',
  CODING_TOOL_NOT_FOUND: 'CODING_TOOL_NOT_FOUND',
  CODING_TOOL_INSTALL_FAILED: 'CODING_TOOL_INSTALL_FAILED',
} as const

export type AppErrorCode = (typeof AppErrorCodes)[keyof typeof AppErrorCodes]
